---
- name: Helpdesk Set Groups
  hosts: "{{ _hosts | default('os_windows') }}"
  gather_facts: false

  tasks:

    - name: Set Group for User {{ firstname }} {{ surname }}
      microsoft.ad.user:
        name: "{{ firstname }} {{ surname }}"
        firstname: "{{ firstname }}"
        surname: "{{ surname }}"
        sam_account_name: "{{ firstname[0] }}{{ surname }}"
        company: BobCo
        state: present
        groups:
          add: "{{ domain_groups }}"
