---
- name: Remove and stop apache
  hosts: web
  become: true
  
  tasks:

    - name: Stop the httpd service if needed
      ansible.builtin.service:
        name: httpd
        state: stopped
      ignore_errors: true
  
    - name: Ensure the httpd package is removed
      ansible.builtin.package:
        name: httpd
        state: absent

    - name: Ensure the index.html file is absent
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

